CREATE TABLE USER(
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   USERNAME TEXT NOT NULL,
   EMAIL TEXT NOT NULL,
   PASSWORD TEXT NOT NULL
);

CREATE TABLE FORGET_PASSWORD_EMAIL(
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   EMAIL TEXT NOT NULL,
   TIME_SENT DATETIME NOT NULL
);
