"""inital

Revision ID: addb1d385cf8
Revises: 
Create Date: 2022-07-19 10:39:54.578154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'addb1d385cf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noti_type',
    sa.Column('NotiTypeID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=64), nullable=True),
    sa.Column('Description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('NotiTypeID')
    )
    op.create_index(op.f('ix_noti_type_Name'), 'noti_type', ['Name'], unique=False)
    op.create_table('raucu',
    sa.Column('RaucuID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=64), nullable=True),
    sa.Column('Type', sa.String(length=128), nullable=True),
    sa.Column('ShopID', sa.Integer(), nullable=True),
    sa.Column('ProductPic', sa.String(length=128), nullable=True),
    sa.Column('Price', sa.Numeric(), nullable=True),
    sa.Column('Description', sa.String(length=512), nullable=True),
    sa.Column('ReviewID', sa.Integer(), nullable=True),
    sa.Column('Discount', sa.Float(), nullable=True),
    sa.Column('TimeCreated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ReviewID'], ['review.ReviewID'], ),
    sa.ForeignKeyConstraint(['ShopID'], ['shop.ShopID'], ),
    sa.PrimaryKeyConstraint('RaucuID')
    )
    op.create_index(op.f('ix_raucu_Name'), 'raucu', ['Name'], unique=True)
    op.create_index(op.f('ix_raucu_TimeCreated'), 'raucu', ['TimeCreated'], unique=False)
    op.create_index(op.f('ix_raucu_Type'), 'raucu', ['Type'], unique=False)
    op.create_table('reset_password_email',
    sa.Column('ResetID', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=128), nullable=True),
    sa.Column('TimeStamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ResetID')
    )
    op.create_index(op.f('ix_reset_password_email_Email'), 'reset_password_email', ['Email'], unique=False)
    op.create_index(op.f('ix_reset_password_email_TimeStamp'), 'reset_password_email', ['TimeStamp'], unique=False)
    op.create_table('review',
    sa.Column('ReviewID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('Stars', sa.Float(), nullable=True),
    sa.Column('Comments', sa.String(length=512), nullable=True),
    sa.Column('ReviewType', sa.Integer(), nullable=True),
    sa.Column('TimeStamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ReviewType'], ['review_type.TypeID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], ),
    sa.PrimaryKeyConstraint('ReviewID')
    )
    op.create_index(op.f('ix_review_TimeStamp'), 'review', ['TimeStamp'], unique=False)
    op.create_table('review_type',
    sa.Column('TypeID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=64), nullable=True),
    sa.Column('RaucuID', sa.Integer(), nullable=True),
    sa.Column('ShopID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['RaucuID'], ['raucu.RaucuID'], ),
    sa.ForeignKeyConstraint(['ShopID'], ['shop.ShopID'], ),
    sa.PrimaryKeyConstraint('TypeID')
    )
    op.create_index(op.f('ix_review_type_Name'), 'review_type', ['Name'], unique=False)
    op.create_table('shop',
    sa.Column('ShopID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=64), nullable=True),
    sa.Column('Address', sa.String(length=256), nullable=True),
    sa.Column('PhoneNo', sa.Numeric(), nullable=True),
    sa.Column('ProfilePic', sa.String(length=128), nullable=True),
    sa.Column('NoSelling', sa.Integer(), nullable=True),
    sa.Column('NoSold', sa.Integer(), nullable=True),
    sa.Column('ReviewID', sa.Integer(), nullable=True),
    sa.Column('TimeCreated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ReviewID'], ['review.ReviewID'], ),
    sa.PrimaryKeyConstraint('ShopID')
    )
    op.create_index(op.f('ix_shop_Address'), 'shop', ['Address'], unique=False)
    op.create_index(op.f('ix_shop_Name'), 'shop', ['Name'], unique=True)
    op.create_index(op.f('ix_shop_TimeCreated'), 'shop', ['TimeCreated'], unique=False)
    op.create_table('user',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(length=64), nullable=True),
    sa.Column('Email', sa.String(length=128), nullable=True),
    sa.Column('PasswordHash', sa.String(length=128), nullable=True),
    sa.Column('ProfilePic', sa.String(length=128), nullable=True),
    sa.Column('PhoneNo', sa.Numeric(), nullable=True),
    sa.Column('Birthday', sa.DateTime(), nullable=True),
    sa.Column('Gender', sa.String(length=16), nullable=True),
    sa.Column('TimeRegistered', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_index(op.f('ix_user_Email'), 'user', ['Email'], unique=True)
    op.create_index(op.f('ix_user_TimeRegistered'), 'user', ['TimeRegistered'], unique=False)
    op.create_index(op.f('ix_user_UserName'), 'user', ['UserName'], unique=True)
    op.create_table('bookmark',
    sa.Column('BookmarkID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('RaucuID', sa.Integer(), nullable=True),
    sa.Column('TimeStamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['RaucuID'], ['raucu.RaucuID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], ),
    sa.PrimaryKeyConstraint('BookmarkID')
    )
    op.create_index(op.f('ix_bookmark_TimeStamp'), 'bookmark', ['TimeStamp'], unique=False)
    op.create_table('cart',
    sa.Column('CartID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('RaucuID', sa.Integer(), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=True),
    sa.Column('TimeStamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['RaucuID'], ['raucu.RaucuID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], ),
    sa.PrimaryKeyConstraint('CartID')
    )
    op.create_index(op.f('ix_cart_TimeStamp'), 'cart', ['TimeStamp'], unique=False)
    op.create_table('notifications',
    sa.Column('NotiID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('RaucuID', sa.Integer(), nullable=True),
    sa.Column('TypeID', sa.Integer(), nullable=True),
    sa.Column('Description', sa.String(length=512), nullable=True),
    sa.Column('TimeStamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['RaucuID'], ['raucu.RaucuID'], ),
    sa.ForeignKeyConstraint(['TypeID'], ['noti_type.NotiTypeID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], ),
    sa.PrimaryKeyConstraint('NotiID')
    )
    op.create_index(op.f('ix_notifications_TimeStamp'), 'notifications', ['TimeStamp'], unique=False)
    op.create_table('reciept',
    sa.Column('RecieptID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('ShippingCost', sa.Numeric(), nullable=True),
    sa.Column('ShippingAddr', sa.Numeric(), nullable=True),
    sa.Column('TotalPrice', sa.Numeric(), nullable=True),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], ),
    sa.PrimaryKeyConstraint('RecieptID')
    )
    op.create_index(op.f('ix_reciept_CreatedTime'), 'reciept', ['CreatedTime'], unique=False)
    op.create_table('selling_list',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('ShopID', sa.Integer(), nullable=True),
    sa.Column('RaucuID', sa.Integer(), nullable=True),
    sa.Column('Quantity', sa.String(length=120), nullable=True),
    sa.Column('Status', sa.String(length=120), nullable=True),
    sa.Column('ItemSold', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['RaucuID'], ['raucu.RaucuID'], ),
    sa.ForeignKeyConstraint(['ShopID'], ['shop.ShopID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_selling_list_ItemSold'), 'selling_list', ['ItemSold'], unique=True)
    op.create_index(op.f('ix_selling_list_Quantity'), 'selling_list', ['Quantity'], unique=True)
    op.create_index(op.f('ix_selling_list_Status'), 'selling_list', ['Status'], unique=True)
    op.create_table('reciept_list',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('RecieptID', sa.Integer(), nullable=True),
    sa.Column('RaucuID', sa.Integer(), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['RaucuID'], ['raucu.RaucuID'], ),
    sa.ForeignKeyConstraint(['RecieptID'], ['reciept.RecieptID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reciept_list')
    op.drop_index(op.f('ix_selling_list_Status'), table_name='selling_list')
    op.drop_index(op.f('ix_selling_list_Quantity'), table_name='selling_list')
    op.drop_index(op.f('ix_selling_list_ItemSold'), table_name='selling_list')
    op.drop_table('selling_list')
    op.drop_index(op.f('ix_reciept_CreatedTime'), table_name='reciept')
    op.drop_table('reciept')
    op.drop_index(op.f('ix_notifications_TimeStamp'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_cart_TimeStamp'), table_name='cart')
    op.drop_table('cart')
    op.drop_index(op.f('ix_bookmark_TimeStamp'), table_name='bookmark')
    op.drop_table('bookmark')
    op.drop_index(op.f('ix_user_UserName'), table_name='user')
    op.drop_index(op.f('ix_user_TimeRegistered'), table_name='user')
    op.drop_index(op.f('ix_user_Email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_shop_TimeCreated'), table_name='shop')
    op.drop_index(op.f('ix_shop_Name'), table_name='shop')
    op.drop_index(op.f('ix_shop_Address'), table_name='shop')
    op.drop_table('shop')
    op.drop_index(op.f('ix_review_type_Name'), table_name='review_type')
    op.drop_table('review_type')
    op.drop_index(op.f('ix_review_TimeStamp'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_reset_password_email_TimeStamp'), table_name='reset_password_email')
    op.drop_index(op.f('ix_reset_password_email_Email'), table_name='reset_password_email')
    op.drop_table('reset_password_email')
    op.drop_index(op.f('ix_raucu_Type'), table_name='raucu')
    op.drop_index(op.f('ix_raucu_TimeCreated'), table_name='raucu')
    op.drop_index(op.f('ix_raucu_Name'), table_name='raucu')
    op.drop_table('raucu')
    op.drop_index(op.f('ix_noti_type_Name'), table_name='noti_type')
    op.drop_table('noti_type')
    # ### end Alembic commands ###
