"""refactor database

Revision ID: c7ddb95eb4af
Revises: 
Create Date: 2022-09-21 08:28:16.089855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ddb95eb4af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_password_email',
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email', 'timestamp')
    )
    op.create_index(op.f('ix_reset_password_email_email'), 'reset_password_email', ['email'], unique=False)
    op.create_index(op.f('ix_reset_password_email_status'), 'reset_password_email', ['status'], unique=False)
    op.create_index(op.f('ix_reset_password_email_timestamp'), 'reset_password_email', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('profile_pic', sa.String(length=128), nullable=True),
    sa.Column('phone_no', sa.String(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_timestamp'), 'user', ['timestamp'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('reciept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(), nullable=True),
    sa.Column('shipping_addr', sa.Numeric(), nullable=True),
    sa.Column('total_price', sa.Numeric(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reciept_timestamp'), 'reciept', ['timestamp'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stars', sa.Float(), nullable=True),
    sa.Column('comments', sa.String(length=512), nullable=True),
    sa.Column('review_type', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_review_type'), 'review', ['review_type'], unique=False)
    op.create_index(op.f('ix_review_timestamp'), 'review', ['timestamp'], unique=False)
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('phone_no', sa.String(), nullable=True),
    sa.Column('profile_pic', sa.String(length=128), nullable=True),
    sa.Column('no_selling', sa.Integer(), nullable=True),
    sa.Column('no_sold', sa.Integer(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_address'), 'shop', ['address'], unique=False)
    op.create_index(op.f('ix_shop_name'), 'shop', ['name'], unique=True)
    op.create_index(op.f('ix_shop_timestamp'), 'shop', ['timestamp'], unique=False)
    op.create_table('raucu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('raucu_type', sa.String(length=128), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('product_pic', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raucu_name'), 'raucu', ['name'], unique=True)
    op.create_index(op.f('ix_raucu_raucu_type'), 'raucu', ['raucu_type'], unique=False)
    op.create_index(op.f('ix_raucu_timestamp'), 'raucu', ['timestamp'], unique=False)
    op.create_table('bookmark',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('raucu_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raucu_id'], ['raucu.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'raucu_id')
    )
    op.create_index(op.f('ix_bookmark_timestamp'), 'bookmark', ['timestamp'], unique=False)
    op.create_table('cart',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('raucu_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raucu_id'], ['raucu.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'raucu_id')
    )
    op.create_index(op.f('ix_cart_timestamp'), 'cart', ['timestamp'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('raucu_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('noti_type', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raucu_id'], ['raucu.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_timestamp'), 'notifications', ['timestamp'], unique=False)
    op.create_table('reciept_list',
    sa.Column('reciept_id', sa.Integer(), nullable=False),
    sa.Column('raucu_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['raucu_id'], ['raucu.id'], ),
    sa.ForeignKeyConstraint(['reciept_id'], ['reciept.id'], ),
    sa.PrimaryKeyConstraint('reciept_id', 'raucu_id')
    )
    op.create_table('selling_list',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('raucu_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('item_sold', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['raucu_id'], ['raucu.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('shop_id', 'raucu_id')
    )
    op.create_index(op.f('ix_selling_list_item_sold'), 'selling_list', ['item_sold'], unique=False)
    op.create_index(op.f('ix_selling_list_quantity'), 'selling_list', ['quantity'], unique=False)
    op.create_index(op.f('ix_selling_list_status'), 'selling_list', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_selling_list_status'), table_name='selling_list')
    op.drop_index(op.f('ix_selling_list_quantity'), table_name='selling_list')
    op.drop_index(op.f('ix_selling_list_item_sold'), table_name='selling_list')
    op.drop_table('selling_list')
    op.drop_table('reciept_list')
    op.drop_index(op.f('ix_notifications_timestamp'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_cart_timestamp'), table_name='cart')
    op.drop_table('cart')
    op.drop_index(op.f('ix_bookmark_timestamp'), table_name='bookmark')
    op.drop_table('bookmark')
    op.drop_index(op.f('ix_raucu_timestamp'), table_name='raucu')
    op.drop_index(op.f('ix_raucu_raucu_type'), table_name='raucu')
    op.drop_index(op.f('ix_raucu_name'), table_name='raucu')
    op.drop_table('raucu')
    op.drop_index(op.f('ix_shop_timestamp'), table_name='shop')
    op.drop_index(op.f('ix_shop_name'), table_name='shop')
    op.drop_index(op.f('ix_shop_address'), table_name='shop')
    op.drop_table('shop')
    op.drop_index(op.f('ix_review_timestamp'), table_name='review')
    op.drop_index(op.f('ix_review_review_type'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_reciept_timestamp'), table_name='reciept')
    op.drop_table('reciept')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_timestamp'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_reset_password_email_timestamp'), table_name='reset_password_email')
    op.drop_index(op.f('ix_reset_password_email_status'), table_name='reset_password_email')
    op.drop_index(op.f('ix_reset_password_email_email'), table_name='reset_password_email')
    op.drop_table('reset_password_email')
    # ### end Alembic commands ###
