CREATE TABLE USER(
   USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
   USERNAME TEXT NOT NULL,
   EMAIL TEXT NOT NULL,
   PASSWORD TEXT NOT NULL,
   PHONE_NO NUMBERIC,
   BIRTHDAY DATETIME,
   GENDER TEXT,
   TIME_REGISTERED DATETIME NOT NULL
);

CREATE TABLE RAUCU(
   RAUCU_ID INTEGER PRIMARY KEY AUTOINCREMENT,
   NAME TEXT,
   TYPE TEXT,
   SHOP_ID INTEGER,
   PRICE INTEGER,
   DESCRIPTION TEXT,
   REVIEW_ID INTEGER,
   TIME_CREATED DATETIME,
   DISCOUNT INTEGER,
   ITEMSOLD INTEGER,
   FOREIGN KEY(SHOP_ID) REFERENCES SHOP(SHOP_ID),
   FOREIGN KEY(REVIEW_ID) REFERENCES REVIEW(REVIEW_ID)
);

CREATE TABLE RECIEPT(
   RECIEPT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
   USER_ID INTEGER,
   SHIPPING_COST INTEGER,
   FINAL_PRICE INTEGER,
   SHIPPING_ADDR TEXT,
   CREATED_TIME DATETIME,
   FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE NOTIFICATIONS(
   NOTI_ID INTEGER PRIMARY KEY AUTOINCREMENT,
   USER_ID INTEGER,
   RAUCU_ID INTEGER,
   TYPE TEXT,
   DESCRIPTION TEXT,
   TIME_STAMP DATETIME NOT NULL,
   FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID),
   FOREIGN KEY(RAUCU_ID) REFERENCES RAUCU(RAUCU_ID)
);

CREATE TABLE RECIEPT_RAUCU_LIST(
   RECIEPT_ID INTEGER,
   RAUCU_ID INTEGER,
   QUANTITY INTEGER,
   FOREIGN KEY(RECIEPT_ID) REFERENCES RECIEPT(RECIEPT_ID),
   FOREIGN KEY(RAUCU_ID) REFERENCES RAUCU(RAUCU_ID)
);

CREATE TABLE CART(
   CART_ID INTEGER PRIMARY KEY AUTOINCREMENT,
   USER_ID INTEGER,
   RAUCU_ID INTEGER,
   QUANTITY INTEGER,
   TIME_STAMP DATETIME,
   FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID),
   FOREIGN KEY(RAUCU_ID) REFERENCES RAUCU(RAUCU_ID)
);

CREATE TABLE BOOKMARK(
   BOOKMARK_ID INTEGER PRIMARY KEY AUTOINCREMENT,
   USER_ID INTEGER,
   RAUCU_ID INTEGER,
   TIME_STAMP DATETIME,
   FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID),
   FOREIGN KEY(RAUCU_ID) REFERENCES RAUCU(RAUCU_ID)
);

CREATE TABLE REVIEW(
   REVIEW_ID INTEGER PRIMARY KEY AUTOINCREMENT,
   USER_ID INTEGER,
   STARS REAL,
   COMMENTS TEXT,
   RAUCU_ID INTEGER,
   SHOP_ID INTEGER,
   TIME_STAMP DATETIME,
   FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID),
   FOREIGN KEY(SHOP_ID) REFERENCES SHOP(SHOP_ID),
   FOREIGN KEY(RAUCU_ID) REFERENCES RAUCU(RAUCU_ID)
);

CREATE TABLE SHOP(
   SHOP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
   NAME TEXT,
   ADDRESS TEXT,
   PHONE_NO NUMBERIC,
   TIME_CREATED DATETIME,
   NO_SELLING_PRODUCTS INTEGER,
   REVIEW_ID INTEGER,
   NO_PRODUCTS_SOLD INTEGER,
   FOREIGN KEY(REVIEW_ID) REFERENCES REVIEW(REVIEW_ID)
);

CREATE TABLE SHOP_RAUCU_LIST(
   SHOP_ID INTEGER,
   RAUCU_ID INTEGER,
   QUANTITY INTEGER,
   FOREIGN KEY(SHOP_ID) REFERENCES SHOP(SHOP_ID),
   FOREIGN KEY(RAUCU_ID) REFERENCES RAUCU(RAUCU_ID)
);

CREATE TABLE FORGET_PASSWORD_EMAIL(
   EMAIL TEXT NOT NULL,
   TIME_STAMP DATETIME NOT NULL
);

